% autoexec_cfg generated by Configure AFC. Add your local preferences here.

%Updated: EJB: 10/27/2014
def.language = 'EN';
def.fileNamingScheme = '%E_%S_%C';
def.deviceID = -1;
def.bits=24;
msg.measure_msg= '--- CORRECT ---';
def.variableCheck = 0;
%def.externSoundCommand = 'soundmexprofree';
def.externSoundCommand = '';
def.internSoundCommand = 'audioplayer';
%def.soundmexproPauseDriver = 1;
%def.audioplayerDelayCompensation=0.2; %200 ms delay added to work.out to sync sound with buttons
def.markIntervalDelay = 0.1; %Compensation for delay using audioplayer
